PW-Sat2/GSControl

gnuradio/downlink/downlink.grc
gnuradio/downlink/source/file_source.grc
gnuradio/downlink/source/file_source_path.grc
gnuradio/downlink/source/funcube_source.grc
gnuradio/downlink/source/funcube_source_source_parameter.grc
gnuradio/downlink/source/plutosdr_source.grc
gnuradio/downlink/source/plutosdr_source_source_parameter.grc
gnuradio/downlink/source/rtl_sdr_source.grc
gnuradio/downlink/source/rtl_sdr_source_source_parameter.grc
gnuradio/downlink/source/ssb_audio_source.grc

Changed frequency xlating to own frequency_shift

---

radio/shell_cmd/tasklist.py

- retry feature
- tasks print instead of analyze when loaded

Tasklist improvements

---

radio/analyzer_engine/commands.py
radio/analyzer_engine/task.py

Correctly recognize and handle non telecommand entries on task list.

Task list analyzer update.

---

gnuradio/downlink/downlink.grc

* Added config options for Frame Files.
* Moved bitrate selector down in GUI.

Downlink chart improvements - GUI and config

---

tools/gpredict_relay.py

now engaging every time is not needed

GPredict proxy

---

tools/grafana_beacon_uploader/app.py

https://www.youtube.com/watch?v=iofT_kc7FH8

Fix uploader again

---

radio/shell_cmd/tasklist.py

- Previous task
- Goto task
- ^C quietly ends tasklist

Mode tasklisk commands:

---

tools/radio_pwsat_pl/download_frame_files.py
tools/radio_pwsat_pl/download_turbo_ola.py

Also added timespan parameter to download_frame_files.

Separate Turbo-Ola file generation from All.Frames file generation.

---

radio/shell_cmd/fast_tc.py

Fast functions:
- setbitrate_1200()
- setbitrate_9600()
- sail()

fast setbitrate and sail

---

tools/monitor_file_list.py

* deduplication of seqs
* change of cid resets list of received seqs

Monitor file list

---

tools/generate_tasklist.py
tools/tasklist_templates/power_cycle_A.template
tools/tasklist_templates/power_cycle_B.template
tools/tasklist_templates/telemetry_download.template

e.g.:
`python generate_tasklist.py -s 191 -e 192 -t ".\tasklist_templates\power_cycle_A.template"`
will generate:
```
tasks = [
[[tc.SetBitrate(1, BaudRate.BaudRate1200), 5], SendLoop, WaitMode.NoWait],
[[tc.SendBeacon(), 20], SendLoop, WaitMode.NoWait],
[tc.ReadMemory(2, 0x8801b620, 248), Send, WaitMode.Wait], # scrubbing
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.RawI2C(3, 0, 0x35, 1, [0xE0]), Send, WaitMode.Wait],
[tc.PingTelecommand(), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.SetBitrate(4, BaudRate.BaudRate9600), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.ListFiles(5, '/'), Send, WaitMode.Wait],
[tc.DownloadFile(30, '/telemetry.previous', [2180, 2230, 2205, 2255, 2193, 2243, 2217, 2267, 2187, 2237, 2199, 2249, 2211, 2261, 2223, 2273, …
```

tasklist generator based on templates

---

tools/generate_tasklist.py
tools/tasklist_templates/power_cycle_A.template
tools/tasklist_templates/power_cycle_B.template
tools/tasklist_templates/take_photos_20.template
tools/tasklist_templates/telemetry_download.template

add basic generation info to tasklist

---

tools/pass_predict/predict_passes.py
tools/pass_predict/prediction.py

* generates n sessions after last session in the repository,
* automatically generate manual sessions with telemetry and power cycle (A/B controllers queue is based on last power cycle in repo)
* adds session tasks description in json for future usage in tasklist generator
Check out http://titan.gajoch.pl/mission/test-brancz/

Extended session generator:

---

auto_session/auto_start_session.py
auto_session/deep_sleep.py
auto_session/execute_session.py
summary/mission_store.py
tools/generate_tasklist.py
tools/grafana_beacon_uploader/app.py
tools/grafana_beacon_uploader/data_point.py
tools/grafana_beacon_uploader/upload_frames_file.py
tools/parse_deep_beacon.py
tools/pass_predict/predict_passes.py
tools/tasklist_templates/refresh_deep_sleep.template
tools/telemetry_loss_notifier.py
tools/upload_software/generate_tasklist.py

* Auto session
* Deep sleep beacon uploader
* Generate `sleep-beacon` task in pass predict

Deep sleep support

---

auto_session/auto_start_session.py

- deep sleep beacon as default auto-session scenario
- fixed normal mode auto session

Auto session in normal mode fix

---

auto_session/auto_start_session.py
tools/receive_radio_pwsat_pl/callsign_decoder.py
tools/receive_radio_pwsat_pl/main.py
tools/receive_radio_pwsat_pl/make_frame_object.py
tools/receive_radio_pwsat_pl/receiver.py

Ham Radio Receive Console v 2.0

Radio pwsat receive improvements

---

summary/mission_store.py
summary/summary_steps/03-files.py
tools/generate_tasklist.py

- sorting missings in `tasklist.missing.py`
- sorting frames in `downlink_rames.txt`
- removing `*.missing` when new run of summary on new frames gets all chunks.

Sorted missings

---

auto_session/roster.py

Operator Mariusz.

---

tools/rotor_offset_proxy.py

Rotor offset fix

---

tools/tasklist_templates/refresh_deep_sleep.template

And reduce time to shift from 40-second main satellite loop.

Loop for ping during wakeup

---

scripts/systemd/gs-gpredict-proxy.service
tools/gpredict_relay.py
tools/grafana_beacon_uploader/app.py
tools/grafana_beacon_uploader/run.py
tools/gs_to_slack_uploader/main.py
tools/gs_to_slack_uploader/receive_distribute.py
tools/gs_to_slack_uploader/slack_upload.py

Preparations for moving several scripts to SystemD.

Moving to Systemd - part 1.

---

tools/monitor/Readme.md
tools/monitor/backend.py
tools/monitor/gui.py
tools/monitor/model.py

- Scrolling.
- Task command number shown.
- User Manual.

Monitor addons
